# Generated by Django 2.2.1 on 2020-10-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quession',
            new_name='Question',
        ),
    ]
